import type { Vehicle, SupplementPlan } from './types'

export const VEHICLES: Vehicle[] = [
  { plateNumber: '京A·88562', cargoType: '冷冻肉类' },
  { plateNumber: '京B·33721', cargoType: '冷藏蔬果' },
  { plateNumber: '沪C·55019', cargoType: '乳制品' },
  { plateNumber: '粤D·66204', cargoType: '医药制品' },
]

export const SUPPLEMENT_PLANS: SupplementPlan[] = [
  {
    id: 'plan-1',
    name: '京东冷链干冰站(亦庄)',
    type: '干冰点',
    address: '北京市亦庄经济开发区科创十三街18号院',
    distance: 3.2,
    detourMinutes: 12,
    isOpen: true,
    capacity: '500kg',
    contactPhone: '13812342210',
    contactName: '张师傅',
    businessHours: '06:00-22:00',
  },
  {
    id: 'plan-2',
    name: '顺丰冷运补给中心(大兴)',
    type: '制冷剂补给点',
    address: '北京市大兴区黄村镇芦花路甲1号',
    distance: 5.8,
    detourMinutes: 18,
    isOpen: true,
    capacity: '200瓶',
    contactPhone: '13912345521',
    contactName: '李主管',
    businessHours: '07:00-21:00',
  },
  {
    id: 'plan-3',
    name: '中冷物流合作冷库(通州)',
    type: '合作冷库',
    address: '北京市通州区马驹桥镇物流基地',
    distance: 8.1,
    detourMinutes: 25,
    isOpen: true,
    capacity: '50吨',
    contactPhone: '13612348832',
    contactName: '王经理',
    businessHours: '24小时',
  },
  {
    id: 'plan-4',
    name: '京台高速安全停车区(A3)',
    type: '安全停车区',
    address: '京台高速K23+500处',
    distance: 1.5,
    detourMinutes: 5,
    isOpen: true,
    capacity: '-',
    contactPhone: '12122',
    contactName: '高速救援',
    businessHours: '24小时',
  },
  {
    id: 'plan-5',
    name: '华北干冰供应站(朝阳)',
    type: '干冰点',
    address: '北京市朝阳区金盏乡楼梓庄路12号',
    distance: 6.5,
    detourMinutes: 20,
    isOpen: false,
    capacity: '300kg',
    contactPhone: '13512344420',
    contactName: '陈师傅',
    businessHours: '08:00-18:00',
  },
  {
    id: 'plan-6',
    name: '万达冷链补给点(丰台)',
    type: '制冷剂补给点',
    address: '北京市丰台区花乡桥南樊家村路甲3号',
    distance: 4.2,
    detourMinutes: 15,
    isOpen: true,
    capacity: '150瓶',
    contactPhone: '13712346633',
    contactName: '赵主管',
    businessHours: '06:30-20:30',
  },
  {
    id: 'plan-7',
    name: '首农冷库(房山)',
    type: '合作冷库',
    address: '北京市房山区窦店镇高端制造业基地',
    distance: 12.3,
    detourMinutes: 35,
    isOpen: true,
    capacity: '80吨',
    contactPhone: '13312349911',
    contactName: '刘经理',
    businessHours: '05:00-23:00',
  },
  {
    id: 'plan-8',
    name: '京津高速安全停车区(B1)',
    type: '安全停车区',
    address: '京津高速K15+200处',
    distance: 2.0,
    detourMinutes: 7,
    isOpen: true,
    capacity: '-',
    contactPhone: '12122',
    contactName: '高速救援',
    businessHours: '24小时',
  },
]
